#!/bin/bash

j=0
for i in 32 64 128 
do
 let j++
./build/ARM/gem5.opt -d script1/specbzip/l1d/specbzip_"$j" configs/example/se.py --cpu-type=MinorCPU --caches --l2cache --l1d_size="$i"kB --l1i_size=32kB --l2_size=512kB --l1d_assoc=1 --l1i_assoc=1 --l2_assoc=2 --cacheline_size=64 --cpu-clock=1GHz -c spec_cpu2006/401.bzip2/src/specbzip -o "spec_cpu2006/401.bzip2/data/input.program 10" -I 100000000

done

j=0
for i in 32 64 128
do
 let j++
./build/ARM/gem5.opt -d script1/specbzip/l1i/specbzip_"$j" configs/example/se.py --cpu-type=MinorCPU --caches --l2cache --l1d_size=64kB --l1i_size="$i"kB --l2_size=512kB --l1d_assoc=1 --l1i_assoc=1 --l2_assoc=2 --cacheline_size=64 --cpu-clock=1GHz -c spec_cpu2006/401.bzip2/src/specbzip -o "spec_cpu2006/401.bzip2/data/input.program 10" -I 100000000

done

j=0
for i in 512 2048 4096
do
 let j++
./build/ARM/gem5.opt -d script1/specbzip/l2/specbzip_"$j" configs/example/se.py --cpu-type=MinorCPU --caches --l2cache --l1d_size=64kB --l1i_size=32kB --l2_size="$i"kB --l1d_assoc=1 --l1i_assoc=1 --l2_assoc=2 --cacheline_size=64 --cpu-clock=1GHz -c spec_cpu2006/401.bzip2/src/specbzip -o "spec_cpu2006/401.bzip2/data/input.program 10" -I 100000000

done

j=0
for i in 1 2 4 8
do
 let j++
./build/ARM/gem5.opt -d script1/specbzip/l1_assoc/specbzip_"$j" configs/example/se.py --cpu-type=MinorCPU --caches --l2cache --l1d_size=64kB --l1i_size=32kB --l2_size=512kB --l1d_assoc=$i --l1i_assoc=$i --l2_assoc=2 --cacheline_size=64 --cpu-clock=1GHz -c spec_cpu2006/401.bzip2/src/specbzip -o "spec_cpu2006/401.bzip2/data/input.program 10" -I 100000000

done

j=0
for i in 1 2 4 8
do
 let j++
./build/ARM/gem5.opt -d script1/specbzip/l2_assoc/specbzip_"$j" configs/example/se.py --cpu-type=MinorCPU --caches --l2cache --l1d_size=64kB --l1i_size=32kB --l2_size=512kB --l1d_assoc=1 --l1i_assoc=1 --l2_assoc=$i --cacheline_size=64 --cpu-clock=1GHz -c spec_cpu2006/401.bzip2/src/specbzip -o "spec_cpu2006/401.bzip2/data/input.program 10" -I 100000000

done

j=0
for i in 32 64 128
do
 let j++
./build/ARM/gem5.opt -d script1/specbzip/cl/specbzip_"$j" configs/example/se.py --cpu-type=MinorCPU --caches --l2cache --l1d_size=64kB --l1i_size=32kB --l2_size=512kB --l1d_assoc=1 --l1i_assoc=1 --l2_assoc=2 --cacheline_size=$i --cpu-clock=1GHz -c spec_cpu2006/401.bzip2/src/specbzip -o "spec_cpu2006/401.bzip2/data/input.program 10" -I 100000000

done


